cs51-college-calendar:
  ical_url: https://canvas.harvard.edu/feeds/calendars/user_K25S2ApW2OVPxzjInXIY3rDsVcEXkSKlnISmCDuO.ics
  rules:
    - field: summary
      operator: contains
      val: '[COMPSCI 51]'

cs51-dce-calendar:
  ical_url: https://canvas.harvard.edu/feeds/calendars/user_K25S2ApW2OVPxzjInXIY3rDsVcEXkSKlnISmCDuO.ics
  rules:
    - field: summary
      operator: contains
      val: 'CSCI E-51'
